# Form implementation generated from reading ui file 'Calculator.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(75, 20))
        self.label.setMaximumSize(QtCore.QSize(75, 20))
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.textBrowser = QtWidgets.QLineEdit(Form)
        self.textBrowser.setMaximumSize(QtCore.QSize(250, 20))
        self.textBrowser.setObjectName("textBrowser")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textBrowser)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(75, 20))
        self.label_2.setMaximumSize(QtCore.QSize(75, 20))
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.textBrowser_2 = QtWidgets.QLineEdit(Form)
        self.textBrowser_2.setMaximumSize(QtCore.QSize(250, 20))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textBrowser_2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMinimumSize(QtCore.QSize(75, 20))
        self.label_3.setMaximumSize(QtCore.QSize(75, 20))
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.textBrowser_3 = QtWidgets.QLineEdit(Form)
        self.textBrowser_3.setMaximumSize(QtCore.QSize(250, 20))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textBrowser_3)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setMinimumSize(QtCore.QSize(75, 20))
        self.label_4.setMaximumSize(QtCore.QSize(75, 20))
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.textBrowser_4 = QtWidgets.QLineEdit(Form)
        self.textBrowser_4.setMaximumSize(QtCore.QSize(250, 20))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textBrowser_4)

        self.button = QtWidgets.QPushButton(text='Calculate Total')
        self.button.pressed.connect(self.calculate)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Principle"))
        self.label_2.setText(_translate("Form", "APR"))
        self.label_3.setText(_translate("Form", "Years"))
        self.label_4.setText(_translate("Form", "Total"))

    def calculate(self): 
        try: 
            principle = float(self.textBrowser.text())
            apr = float(self.textBrowser_2.text()) / 100
            years = int(self.textBrowser_3.text())
            
            total = principle * (1.0 + apr) ** years

            totalString = f'{total:.2f}'
            self.textBrowser_4.setText(totalString)

            total = principle
            x = [i for i in range(years+1)]
            y = []
            for year in x: 
                print(year, total)
                y.append(total)
                total += apr * total

            d = {'Value in $': y}
            data = pd.DataFrame(d)
            data.head()
            plt.clf()
            plt.close()
            sns.lineplot(data = data)
            plt.show()

        except Exception as e : 
            print(e)



app = QtWidgets.QApplication([])
window = QtWidgets.QWidget()

ui = Ui_Form()
ui.setupUi(window)
ui.retranslateUi(window)

window.show()

app.exec()
